name: Automatic Unit Testing
run-name: Automatic Unit Testing (Linux)
on: [push]
jobs:
  Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow triggered by a ${{ github.event_name }} event
        run: echo ""

      - name: Operating system is ${{ runner.os }}
        run: echo ""

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.39.0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21.0.1

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.9.4

      - name: Set up Julia package
        run: echo 'import Pkg; Pkg.add("JSON")' | julia

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4

      - name: Check out repository code from ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Call run-tests.sh
        run: bash run-tests.sh

      - name: Job status is ${{ job.status }}
        run: echo ""
