name: Automatic Unit Testing
run-name: Automatic Unit Testing (Linux)
on: [push]
jobs:
  Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow triggered by a ${{ github.event_name }} event
        run: echo ""

      - name: Operating system is ${{ runner.os }}
        run: echo ""

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Setup Juliu
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.9.4

      - name: Setup Juliu package
        run: echo 'import Pkg; Pkg.add("JSON")' | julia

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: 

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4

      - name: Check out repository code from ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Call run-tests.bat
        run: bash run-tests.sh

      - name: Job status is ${{ job.status }}
        run: echo ""
