name: Automatic Unit Testing
run-name: Automatic Unit Testing (Linux)
on: [push]
jobs:
  Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow triggered by a ${{ github.event_name }} event
        run: echo ""

      - name: Operating system is ${{ runner.os }}
        run: echo ""

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.0.0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21.0.4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.11.0

      - name: Set up Julia package
        run: echo 'import Pkg; Pkg.add("JSON")' | julia

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3.12
          extensions: 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.0

      - name: Check out repository code from ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Call run-tests.sh
        run: bash run-tests.sh

      - name: Job status is ${{ job.status }}
        run: echo ""
